MiraLand/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mdp/", include('mot_de_passe.urls')),
    path("", include('accueil.urls')),
    path("quiz/", include('quizzes.urls'))

]

accueil/urls.py
#Importons les modules nécessaires
from django.urls import path
from accueil import views

#Définissons les routes vers nos vues
urlpatterns = [
    path('connexion/', views.connexion, name = "connexion"),
    path('inscription/', views.inscription, name = "inscription"),
    path('', views.accueil, name = "accueil"),
    path('deconnexion/', views.deconnexion, name = "deconnexion"),


]

quizzes/urls.py
from django.urls import path, include
from rest_framework import routers, viewsets
from .views import(
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    Score,

    # Viewset of Api
    QuizViewSet,
    AnswerViewSet,
    ResultViewSet,
    QuestionViewSet,
)
# API Django Rest
router = routers.DefaultRouter()
router.register(r'quizz', QuizViewSet)
router.register(r'question', QuestionViewSet)
router.register(r'answer', AnswerViewSet)
router.register(r'resultat', ResultViewSet)




app_name = 'quizzes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main_view'),
    path('score', Score, name='score'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),


        # API Django Rest
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

accueil/models.py
from django.db import models

# Create your models here.

accueil/forms.py
#Importons les modules nécessaires
from django import forms
from django.contrib.auth.models import User

"""
    Créons le formulaire de connexion
"""
class ConnexionForm(forms.Form):
    username = forms.CharField(label="Identifiant", max_length=50, widget=forms.TextInput(attrs={'type':'text', 'class':'form-control form-control-user', 'id':'exampleInputEmail', 'aria-describedby':'emailHelp', 'placeholder':'Saisissez votre email...'}))   
    password = forms.CharField(label="Mot-de-passe", widget=forms.PasswordInput(attrs={'type':'password', 'class':'form-control form-control-user', 'id':'exampleInputPassword',  'placeholder':'Saisissez votre mot-de-passe...'}))


"""
    Créons le formulaire d'inscription
"""
class InscriptionForm(forms.Form):
    # first_name = forms.CharField(label="First Name", max_length=100, widget=forms.TextInput(attrs={'class' : 'form-control form-control-user', 'type': 'exampleFirstName', 'placeholder': 'First Name'}))
    # last_name = forms.CharField(label="Last Name", max_length=100, widget=forms.TextInput(attrs={'class' : 'form-control form-control-user', 'type': 'exampleFirstName', 'placeholder': 'Last Name'}))
    username = forms.CharField(label="Identifiant", max_length=50, widget=forms.TextInput(attrs={'class' : 'form-control form-control-user', 'type': 'exampleFirstName', 'placeholder': 'Saisissez votre identifiant...'}))
    email = forms.EmailField(label="Email", widget=forms.TextInput(attrs={'type':'text', 'class':'form-control form-control-user', 'id':'exampleInputEmail', 'aria-describedby':'emailHelp', 'placeholder':'Saisissez votre email...'}))   
    password = forms.CharField(label="Mot-de-passe", widget=forms.TextInput(attrs={'type':'password', 'class':'form-control form-control-user', 'id':'exampleInputPassword',  'placeholder':'Saisissez votre mot-de-passe...'}))

accueil/views.py
#Importons les modules nécessaires
from django.shortcuts import render, redirect
from .forms import ConnexionForm, InscriptionForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


"""
    Créons la vue d'accueil, à partir d'où nous pourrons accéder aux visualisations
"""
# @login_required
def accueil(request):
    return render(request, 'accueil.html')

"""
    Créons la vue pour le formulaire de connexion
"""
def connexion(request):
    #Chargeaons le formulaire de connexion
    form = ConnexionForm(request.POST)
    print()
    if form.is_valid():
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        print(username)
        #Testons la connexion avec les informations de l'utilisateur
        user = authenticate(username = username, password = password)
        if user : 
            login(request, user)
            return render(request, 'accueil.html', locals())
        else:
            error = True
            return render(request, 'connexion.html', locals())
    else:
        form = ConnexionForm()

        return render(request, 'connexion.html', locals())

"""
    Créons la vue pour le formulaire d'Inscription
"""
def inscription(request):
    #Chargeaons le formulaire d'inscription
    form = InscriptionForm(request.POST)
    print(form.is_valid())
    if form.is_valid():
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        # first_name = form.cleaned_data["first_name"]
        # last_name = form.cleaned_data["last_name"]
        email = form.cleaned_data["email"]
        print(email)


        #Insérons un nouvel utilisateur dans la BDD à l'aide de la méthode create_user
        user = User.objects.create_user(username = username, email = email, password = password)
         
        # user.first_name, user.last_name = first_name, last_name
        # user.save()

        #Authentifions le nouvel utilisateur
        user = authenticate(username = username, password = password)
        login(request, user)

        return render(request, 'accueil.html', locals())
    else:
        form = InscriptionForm()

        return render(request, 'inscription.html', locals())

@login_required
def deconnexion(request):
    logout(request)

    return redirect('connexion')

accueil/templates/accueil.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Accueil</title>

  <!-- Bootstrap CSS  -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <!-- bootstrap JS  -->
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
   
</head>

<body id="page-top" style="background-color: #001f3f;">
    <h1 class="text-center text-white">Accueil des Jeux</h1>
    {% if user.is_authenticated %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end p-3">
            <a href="{% url 'deconnexion' %}" type="button" class="btn btn-outline-danger fs-4 text-white">Déconnexion</a>
        </div>
    {% else %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end p-3">
            <!-- <a href="{% url 'connexion' %}" type="button" class="btn btn-outline-danger fs-4 text-white">Connexion</a> -->
            <a href="{% url 'connexion' %}" type="button" class="btn btn-outline-primary fs-4 text-white">Connexion</a>

        </div>
    {% endif %}
    

    <div class=" row">
        <div class="col-6 p-5">
            <a href="{% url 'mot_de_passe' %}">
                <div class="card text-white shadow" style="background-color: #0074D9;">
                    <div class="card-body">
                    Mot-de-passe
                        <div class="text-white-50 small">Devinez le mot-de-passe</div>
                        <i class="fas fa-building"></i>
                    </div>
                    
                </div>
                
            </a>
        </div>

        <div class="col-2 p-5">
            <a class="btn btn-primary" href="{% url 'scores_mdp' %}" style="background-color: #DDDDDD; color: black;">Scores</a>
        </div>

    </div>

    <div class=" row">
        <div class="col-6 p-5">
            <a href="{% url 'quizzes:main_view' %}">
                <div class="card text-white shadow" style="background-color: #0074D9;">
                    <div class="card-body">
                    Quizz Dine (Quizz Dine)
                        <div class="text-white-50 small">Des quiz sur l'Islam...</div>
                        <i class="fas fa-building"></i>
                    </div>
                    
                </div>
                
            </a>
        </div>

        <div class="col-2 p-5">
            <a class="btn btn-primary" href="{% url 'quizzes:score' %}" style="background-color: #DDDDDD; color: black;">Scores</a>
        </div>

    </div>
    
</body>

</html>

accueil/templates/connexion.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Connexion</title>

  <!-- Bootstrap CSS  -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <!-- bootstrap JS  -->
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  
</head>

<body id="page-top" style="background-color: #001f3f;">

              <div class="container">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                      <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                          <div class="col-lg-5 d-none d-lg-block bg-register-image ">
                            <div class="text-center p-5">
                                <!-- <h1 class="h4 text-gray-900 mb-4">Connexion</h1> -->
                                <h3 class="h3 text-gray-900 mb-4">Bienvenue sur notre Plateforme de Jeux, <h1>Miraland</h1> Amusez-vous bien !</h3>
                            </div>
                              <!-- Bienvenue sur notre Plateforme de Jeux, <h3>Miraland</h3>. <br> Amusez-vous bien ! -->
                          </div>
                          <div class="col-lg-7">
                            <div class="p-5">
                              <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Connexion</h1>
                              </div>
                
                              {% if user.is_authenticated %}
                                <h3>Vous êtes connecté, {{ user.username }} !</h3>
                                <div class="text-center">
                                    <a class="small" href="{% url 'accueil' %}">Dirigez-vous vers l'accueil</a>
                                </div>
                            {% else %}
                              <form method="POST" class="user">
                                  {% csrf_token %}
                                  {{ form.as_p }}
                                  <button type="submit" class="btn btn-primary btn-user btn-block">Se connecter</button>
                              </form>
                              <hr>
                              <div class="text-center">
                                <a class="small" href="forgot-password.html">Mot-de-passe oublié?</a>
                              </div>
                              <div class="text-center">
                                <a class="small" href="{% url 'inscription' %}">Vous n'avez pas encore de compte ? Inscrivez-vous vite !</a>
                            </div>
                              {% endif %}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                
                  </div>
</body>

</html>

accueil/templates/inscription.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Inscription</title>

  <!-- Bootstrap CSS  -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

</head>

<body class="bg-gradient-prim" style="background-color: #001f3f;">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image">
            <div class="text-center p-5">
                <!-- <h1 class="h4 text-gray-900 mb-4">Connexion</h1> -->
                <h3 class="h3 text-gray-900 mb-4">Bienvenue sur notre Plateforme de Jeux, <h1>Miraland</h1> Amusez-vous bien !</h3>
            </div>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Inscription</h1>
              </div>

              {% if error %}
                  <p><strong>Utilisateur existe déjà.</strong></p>
              {% endif %}
              <form method="POST" class="user">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-primary btn-user btn-block">S'inscrire</button>
              </form>
              <hr>
              
              <div class="text-center">
                <a class="small" href="{% url 'connexion' %}">Vous avez déjà un compte? Connectez-vous!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  
</body>

</html>